language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-25.0.1
    - platform-tools
    - extra-android-m2repository
    - extra-android-support

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25

before_install:
 - chmod +x gradlew

script:
 - ./gradlew assembleRelease